title: My Jekyll Site
description: A simple static site powered by Jekyll.
url: "https://globalbi.site"  # 改成你的域名或 GitHub Pages 地址
baseurl: "globalbusinessinsight.github.io"     # 如果是项目页，请写 "/your-repo-name"

theme: minima

plugins:
  - jekyll-sitemap
  - jekyll-feed

author:
  name: Paul
  email: cnpaulhu@gmail.com

# Optional: uncomment if you use navigation
# header_pages:
#   - about.md
