<<<<<<< HEAD
title: My Jekyll Site
description: A simple static site powered by Jekyll.
url: "https://globalbi.site"  # 改成你的域名或 GitHub Pages 地址
baseurl: "globalbusinessinsight.github.io"     # 如果是项目页，请写 "/your-repo-name"

theme: minima

plugins:
  - jekyll-sitemap
  - jekyll-feed

author:
  name: Paul
  email: cnpaulhu@gmail.com

# Optional: uncomment if you use navigation
# header_pages:
#   - about.md
=======

title: Global Business Insight
description: A multilingual Jekyll site with four themes
baseurl: ""
url: "https://globalbi.site"
theme: minima
collections:
  posts:
    output: true
plugins:
  - jekyll-feed
  - jekyll-paginate
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: site.author
paginate: 5
paginate_path: "/page:num"
>>>>>>> 21fbad0c080b12b5e28c7c787253840475572f73
