'use strict';
(() => {
const $ = id => document.getElementById(id);
const CONFIG = {NASDAQ:{name:'Nasdaq',color:'#098978',unit:'点'},SP500:{name:'标普 500',color:'#5578cb',unit:'点'},QQQ:{name:'QQQ',color:'#a283be',unit:'美元'},FEDFUNDS:{name:'联邦基金利率',unit:'%'},GS10:{name:'10 年期国债',unit:'%'},GS2:{name:'2 年期国债',unit:'%'},NFP:{name:'新增非农就业',unit:'千人'},GDP_GROWTH:{name:'实际 GDP 增速',unit:'%'}};
const keys=['NASDAQ','SP500','QQQ'];
const state={data:null,rows:[],range:[],start:'',end:'',focus:'',mode:'indexed',macro:'FEDFUNDS',visible:new Set(keys),preset:'20',followNow:true};
const valid=v=>typeof v==='number'&&Number.isFinite(v);
const fmt=(v,d=2)=>valid(v)?v.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const signed=(v,d=2)=>valid(v)?`${v>0?'+':''}${fmt(v,d)}`:'—';
const percent=(a,b)=>valid(a)&&valid(b)&&b!==0?(a/b-1)*100:null;
const shiftMonth=(month,offset)=>{const [y,m]=month.split('-').map(Number);const d=new Date(Date.UTC(y,m-1+offset,1));return d.toISOString().slice(0,7);};
const quarter=month=>`${month.slice(0,4)}-${String(Math.floor((Number(month.slice(5))-1)/3)*3+1).padStart(2,'0')}`;
const nyMonth=()=>{const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit'}).formatToParts(new Date());return p.find(x=>x.type==='year').value+'-'+p.find(x=>x.type==='month').value;};
function validate(data){if(data?.schemaVersion!==1||!data.series)throw Error('数据文件格式不正确');for(const k of [...keys,'FEDFUNDS','PAYEMS','GDPC1','GDP','GS2','GS10']){const s=data.series[k];if(!s||!Array.isArray(s.observations)||!s.observations.length||s.observations.some(o=>!/^\d{4}-\d{2}-\d{2}$/.test(o.date)||!valid(o.value)))throw Error('数据文件缺少有效的 '+k);}return data;}
function makeRows(data,asOf=nyMonth()){const maps={};for(const [k,s] of Object.entries(data.series)) maps[k]=Object.fromEntries(s.observations.map(o=>[o.date.slice(0,7),o]));const months=keys.flatMap(k=>Object.keys(maps[k])).sort();const out=[];for(let m=months[0];m<=asOf;m=shiftMonth(m,1)){const r={month:m,dates:{},times:{},partial:m===asOf||keys.some(k=>maps[k]?.[m]?.provisional)};for(const k of [...keys,'FEDFUNDS','GS2','GS10','PAYEMS']){r[k]=maps[k]?.[m]?.value??null;r.dates[k]=maps[k]?.[m]?.date??null;r.times[k]=maps[k]?.[m]?.asOf??null;}r.NFP=valid(r.PAYEMS)&&valid(maps.PAYEMS[shiftMonth(m,-1)]?.value)?r.PAYEMS-maps.PAYEMS[shiftMonth(m,-1)].value:null;const q=quarter(m);r.quarter=`${q.slice(0,4)} Q${Math.ceil(Number(q.slice(5))/3)}`;r.GDP=maps.GDP[q]?.value??null;r.GDPC1=maps.GDPC1[q]?.value??null;const prev=maps.GDPC1[shiftMonth(q,-3)]?.value;r.GDP_GROWTH=valid(r.GDPC1)&&valid(prev)&&prev>0?((r.GDPC1/prev)**4-1)*100:null;for(const k of keys)r[k+'_return']=percent(r[k],maps[k]?.[shiftMonth(m,-1)]?.value);out.push(r);}return out;}
function notify(message){$('notice').textContent=message;$('notice').hidden=!message;}
function followRange(current,first,last){
  if(!current.followNow)return current;
  const focus=current.focus===current.end?last:current.focus;
  const start=current.preset==='all'?first:current.preset?[first,shiftMonth(last,-Number(current.preset)*12+1)].sort().at(-1):current.start;
  return {...current,start,end:last,focus};
}
function setData(data,initial=false){state.data=validate(data);state.rows=makeRows(data);const first=state.rows[0].month,last=state.rows.at(-1).month;for(const id of ['start','end','focus-month']){$(id).min=first;$(id).max=last;}if(initial){
  let saved;try{saved=JSON.parse(localStorage.getItem('market-atlas-preferences'));}catch{}
  state.end=last;state.start=[first,shiftMonth(last,-239)].sort().at(-1);state.focus=last;
  if(saved&&saved.start>=first&&saved.end<=last&&saved.start<=saved.end){
    const migrated=typeof saved.followNow!=='boolean';
    Object.assign(state,{start:saved.start,end:saved.end,focus:saved.focus||saved.end,
      followNow:migrated?true:saved.followNow,
      preset:['1','3','5','10','20','all'].includes(saved.preset)?saved.preset:migrated?'20':null,
      mode:['indexed','returns'].includes(saved.mode)?saved.mode:'indexed',
      macro:(CONFIG[saved.macro]&&!keys.includes(saved.macro)||saved.macro==='none')?saved.macro:'FEDFUNDS'});
    if(migrated)state.focus=state.end;
  }
}
Object.assign(state,followRange(state,first,last));
$('macro').value=state.macro;render();const failures=Object.values(data.series).filter(s=>s.status!=='ok').length;const age=(Date.now()-Date.parse(data.dataUpdatedAt))/86400000;const stale=age>2||failures;const health=$('health');health.classList.toggle('warning',!!stale);health.textContent=failures?`${failures} 个来源更新失败`:age>2?'数据快照待更新':'历史数据已载入';$('updated').textContent='抓取于 '+new Date(data.dataUpdatedAt).toLocaleString('zh-CN',{timeZone:'America/New_York',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})+' 美东';$('source-status').replaceChildren();for(const [k,s] of Object.entries(data.series)){const line=document.createElement('div');line.className='source-line';const a=document.createElement('a');a.href=s.url;a.target='_blank';a.rel='noreferrer';a.textContent=k;const status=document.createElement('span');status.textContent=`截至 ${s.observations.at(-1).date} · ${s.status==='ok'?'抓取成功':'保留旧值'} · ${s.fetchedAt.slice(0,10)}`;line.append(a,status);$('source-status').append(line);}if(failures)notify('部分来源本次更新失败，已保留上次有效历史数据。请查看下方“更新、历史保存与数据状态”。');else if(age>2)notify('这是保存的历史快照，最近抓取已超过 48 小时。部署并启用定时更新后将自动取得新数据。');else notify('');}
function save(){try{localStorage.setItem('market-atlas-preferences',JSON.stringify({start:state.start,end:state.end,focus:state.focus,mode:state.mode,macro:state.macro,followNow:state.followNow,preset:state.preset}));}catch{}}
function render(){$('follow-now').checked=state.followNow;$('follow-caption').textContent=state.followNow?'结束月份自动延伸到当前月份':'时间范围已固定';state.range=state.rows.filter(r=>r.month>=state.start&&r.month<=state.end);if(!state.range.length)return;if(state.focus<state.start||state.focus>state.end)state.focus=state.end;$('start').value=state.start;$('end').value=state.end;$('focus-month').min=state.start;$('focus-month').max=state.end;$('focus-month').value=state.focus;$('range-caption').textContent=`${state.start.replace('-',' / ')} — ${state.end.replace('-',' / ')} · ${state.range.length} 个月`;$('sample-count').textContent=`${state.range.length} 个月度观察点`;document.querySelectorAll('[data-years]').forEach(b=>b.classList.toggle('selected',b.dataset.years===state.preset));document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===state.mode));$('chart-subtitle').textContent=state.mode==='indexed'?'区间起点 = 100 · 点击图表查看当月':'较上月收盘涨跌 % · 点击图表查看当月';$('legend').innerHTML=keys.map(k=>`<button data-key="${k}" class="${state.visible.has(k)?'':'off'}" aria-pressed="${state.visible.has(k)}"><i class="swatch" style="background:${CONFIG[k].color}"></i>${CONFIG[k].name}</button>`).join('');renderChart();renderFocus();renderTable();save();}
function spark(k){const idx=state.rows.findIndex(r=>r.month===state.focus);const vals=state.rows.slice(Math.max(0,idx-17),idx+1).map(r=>r[k]).filter(valid);if(vals.length<2)return '';const min=Math.min(...vals),max=Math.max(...vals);const p=vals.map((v,i)=>`${i?'L':'M'}${i/(vals.length-1)*90},${32-(v-min)/(max-min||1)*27}`).join(' ');return `<svg class="spark" viewBox="0 0 90 35" aria-hidden="true"><path d="${p}" stroke="${CONFIG[k]?.color||'#d88630'}" fill="none" stroke-width="1.6"/></svg>`;}
function observationLabel(k,r){
  if(!valid(r[k]))return '该月尚无已发布数据';
  const q=state.data.series[k]?.latestQuote;
  if(r.partial&&q?.date?.slice(0,7)===r.month)return '月内暂值 · '+new Date(q.asOf).toLocaleString('zh-CN',{timeZone:'America/New_York',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})+' 美东';
  return k==='FEDFUNDS'?'观察期 '+r.month+' · 月均':'收盘日期 '+r.dates[k];
}
function renderFocus(){const r=state.rows.find(r=>r.month===state.focus);if(!r)return;$('focus-month').value=r.month;$('metrics').innerHTML=[...keys,'FEDFUNDS'].map(k=>{const ch=k==='FEDFUNDS'?(()=>{const p=state.rows.find(x=>x.month===shiftMonth(r.month,-1));return valid(r[k])&&valid(p?.[k])?r[k]-p[k]:null;})():r[k+'_return'];return `<article class="metric"><div class="metric-label"><span>${CONFIG[k].name}</span><small>${k==='NASDAQ'?'IXIC':k==='SP500'?'S&P 500':k==='QQQ'?'NASDAQ ETF':'FED FUNDS'}</small></div><div class="metric-value">${fmt(r[k])}<span class="metric-unit">${k==='FEDFUNDS'?'%':k==='QQQ'?'$':''}</span></div><div class="metric-bottom"><span class="${ch>=0?'positive':'negative'}">${valid(ch)?signed(ch)+(k==='FEDFUNDS'?' pp':'%'):'—'}</span> <span>较上月 · ${r.month}</span></div><div class="metric-asof">${observationLabel(k,r)}</div>${spark(k)}</article>`;}).join('');const items=[['联邦基金利率',valid(r.FEDFUNDS)?fmt(r.FEDFUNDS)+'%':'—'],['新增非农就业',valid(r.NFP)?signed(r.NFP,0)+' 千人':'—'],['实际 GDP 增速',valid(r.GDP_GROWTH)?signed(r.GDP_GROWTH)+'%':'—'],['名义 GDP · 年率',valid(r.GDP)?fmt(r.GDP/1000)+' 万亿美元':'—'],['2 年国债收益率',valid(r.GS2)?fmt(r.GS2)+'%':'—'],['10 年国债收益率',valid(r.GS10)?fmt(r.GS10)+'%':'—']];$('snapshot-values').innerHTML=items.map(([a,b])=>`<div class="snapshot-row"><span>${a}</span><b>${b}</b></div>`).join('');$('snapshot-note').textContent=`${r.partial?'该月市场数据为最新已取得报价或收盘的月内暂值，并非实时推送。':''}GDP 对应 ${r.quarter}，增速为季环比年化。缺失项不使用其他月份的值填充。`;$('month-slider').min=0;$('month-slider').max=state.range.length-1;$('month-slider').value=state.range.findIndex(x=>x.month===r.month);$('slider-min').textContent=state.start;$('slider-max').textContent=state.end;document.querySelectorAll('#table-body tr').forEach(el=>el.classList.toggle('focused',el.dataset.month===r.month));}
function chartSeries(){return keys.filter(k=>state.visible.has(k)).map(k=>{const base=state.range[0][k];return {key:k,values:state.range.map(r=>state.mode==='returns'?r[k+'_return']:valid(base)&&base!==0&&valid(r[k])?r[k]/base*100:null)};});}
function bounds(values){const vals=values.filter(valid);if(!vals.length)return [0,1];let lo=Math.min(...vals),hi=Math.max(...vals);let pad=(hi-lo)*.1||Math.max(Math.abs(hi)*.1,1);return [lo-pad,hi+pad];}
const P={left:62,right:925,top:30,bottom:302};
function xAt(i){return state.range.length===1?(P.left+P.right)/2:P.left+i/(state.range.length-1)*(P.right-P.left);}
function renderChart(){const width=Math.max(320,$('chart-wrap').clientWidth);P.left=55;P.right=width-55;$('chart').setAttribute('viewBox',`0 0 ${width} 355`);const series=chartSeries(),macro=state.macro==='none'?null:CONFIG[state.macro];const mb=state.range.map(r=>r[state.macro]);const left=bounds(series.flatMap(s=>s.values)),right=bounds(mb);const y=(v,b)=>P.bottom-(v-b[0])/(b[1]-b[0])*(P.bottom-P.top);let svg=`<defs><clipPath id="plot-clip"><rect x="${P.left-3}" y="${P.top-3}" width="${P.right-P.left+6}" height="${P.bottom-P.top+6}"/></clipPath></defs><text x="${P.left}" y="14" class="axis-name">${state.mode==='indexed'?'起点 = 100':'月涨跌 %'}</text>`;if(macro)svg+=`<text x="${P.right}" y="14" text-anchor="end" class="axis-name">${macro.unit}</text>`;for(let i=0;i<5;i++){const yy=P.top+i/4*(P.bottom-P.top);svg+=`<line x1="${P.left}" y1="${yy}" x2="${P.right}" y2="${yy}" stroke="#e8eef1" stroke-dasharray="3 4"/><text x="${P.left-12}" y="${yy+4}" text-anchor="end">${fmt(left[1]-i/4*(left[1]-left[0]),state.mode==='returns'?1:0)}</text>`;if(macro)svg+=`<text x="${P.right+12}" y="${yy+4}">${fmt(right[1]-i/4*(right[1]-right[0]),state.macro==='NFP'?0:1)}</text>`;}
const n=state.range.length;const indices=[...new Set(Array.from({length:Math.min(n,width<500?3:width<750?5:7)},(_,i)=>Math.round(i/Math.max(1,Math.min(n,width<500?3:width<750?5:7)-1)*(n-1))))];for(const i of indices)svg+=`<text x="${xAt(i)}" y="332" text-anchor="middle">${state.range[i].month}</text>`;
function path(values,b,color,dashed=false){let d='',active=false;values.forEach((v,i)=>{if(valid(v)){d+=`${active?'L':'M'}${xAt(i).toFixed(2)},${y(v,b).toFixed(2)} `;active=true;}else active=false;});const points=values.map((v,i)=>valid(v)&&(n<3||!valid(values[i-1])&&!valid(values[i+1]))?`<circle cx="${xAt(i)}" cy="${y(v,b)}" r="3" fill="${color}"/>`:'').join('');return `<g clip-path="url(#plot-clip)"><path d="${d}" fill="none" stroke="${color}" stroke-width="${dashed?1.8:2.5}" ${dashed?'stroke-dasharray="5 5"':''} stroke-linejoin="round"/>${points}</g>`;}
if(macro)svg+=path(mb,right,'#d88630',true);for(const s of series)svg+=path(s.values,left,CONFIG[s.key].color);if(series.every(s=>s.values.every(v=>!valid(v))))svg+=`<text x="${width/2}" y="170" text-anchor="middle">此区间无可绘制的市场数据</text>`;svg+='<line id="crosshair" y1="30" y2="302" stroke="#8a9da8" stroke-dasharray="3 4" visibility="hidden"/>';$('chart').innerHTML=svg;$('chart').setAttribute('aria-label',`${state.start} 至 ${state.end}，${state.mode==='indexed'?'归一化市场走势':'市场月度涨跌'}。完整数值见月度明细表。`);$('macro-key').textContent=macro?`${macro.name}${state.macro==='GDP_GROWTH'?'（季度）':''}`:'未叠加指标';$('tooltip').hidden=true;}
function renderTable(){const fields=['NASDAQ','SP500','QQQ','FEDFUNDS','NFP','GDP_GROWTH','GS2','GS10'];$('row-count').textContent=`${state.range.length} 个月`;$('table-body').innerHTML=[...state.range].reverse().map(r=>`<tr data-month="${r.month}" class="${r.month===state.focus?'focused':''}" tabindex="0" aria-label="查看 ${r.month} 快照"><td>${r.month}${r.partial?' <small>月内暂值</small>':''}</td>${fields.map(k=>`<td${k==='NFP'?' class="'+(r[k]>=0?'positive':'negative')+'"':''}>${fmt(r[k],k==='NFP'?0:2)}</td>`).join('')}</tr>`).join('');}
function selectFocus(month){if(month<state.start||month>state.end)return;state.focus=month;renderFocus();save();}
function applyRange(){if(!state.data)return;const start=$('start').value,end=$('end').value;if(!start||!end||start>end){notify('请选择有效的起止月份，起始月份不能晚于结束月份。');return;}if(start<state.rows[0].month||end>state.rows.at(-1).month){notify(`可选范围为 ${state.rows[0].month} 至 ${state.rows.at(-1).month}。`);return;}notify('');state.start=start;state.end=end;state.preset=null;state.followNow=false;render();}
$('follow-now').addEventListener('change',()=>{
  state.followNow=$('follow-now').checked;
  if(state.followNow&&state.data){state.rows=makeRows(state.data);state.focus=state.end;Object.assign(state,followRange(state,state.rows[0].month,nyMonth()));}
  render();if(state.followNow)refresh(true);
});
$('apply').addEventListener('click',applyRange);['start','end'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter')applyRange();}));document.querySelectorAll('[data-years]').forEach(b=>b.addEventListener('click',()=>{if(!state.data)return;state.preset=b.dataset.years;state.followNow=true;state.focus=nyMonth();state.end=state.rows.at(-1).month;state.start=state.preset==='all'?state.rows[0].month:[shiftMonth(state.end,-Number(state.preset)*12+1),state.rows[0].month].sort().at(-1);notify('');render();}));document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;render();}));$('macro').addEventListener('change',()=>{state.macro=$('macro').value;render();});$('legend').addEventListener('click',e=>{const k=e.target.closest('button')?.dataset.key;if(!k)return;if(state.visible.has(k)){if(state.visible.size===1)return;state.visible.delete(k);}else state.visible.add(k);render();});$('focus-month').addEventListener('change',()=>{const m=$('focus-month').value;if(m>=state.start&&m<=state.end)selectFocus(m);else{notify('快照月份需要位于当前选择的时间范围内。');$('focus-month').value=state.focus;}});$('month-slider').addEventListener('input',()=>selectFocus(state.range[Number($('month-slider').value)].month));$('table-body').addEventListener('click',e=>{const m=e.target.closest('tr')?.dataset.month;if(m)selectFocus(m);});$('table-body').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectFocus(e.target.closest('tr').dataset.month);}});
function hover(e,pin=false){if(!state.range.length)return;const svg=$('chart'),matrix=svg.getScreenCTM();if(!matrix)return;const pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());const index=Math.max(0,Math.min(state.range.length-1,Math.round((pt.x-P.left)/(P.right-P.left)*(state.range.length-1))));const row=state.range[index];const line=$('crosshair');line.setAttribute('x1',xAt(index));line.setAttribute('x2',xAt(index));line.setAttribute('visibility','visible');const macro=state.macro==='none'?null:CONFIG[state.macro];$('tooltip').innerHTML=`<strong>${row.month}${row.partial?' · 月内暂值':''}</strong>`+chartSeries().map(s=>`<div class="tooltip-row"><span style="color:${CONFIG[s.key].color==='\x23098978'?'#69daba':CONFIG[s.key].color}">${CONFIG[s.key].name}</span><span>${fmt(s.values[index])}${state.mode==='returns'?'%':''}</span></div>`).join('')+(macro?`<div class="tooltip-row"><span style="color:#edb573">${macro.name}</span><span>${fmt(row[state.macro],state.macro==='NFP'?0:2)} ${macro.unit}</span></div>`:'');const tip=$('tooltip');tip.hidden=false;const wrap=$('chart-wrap').getBoundingClientRect();tip.style.left=Math.max(4,Math.min(wrap.width-tip.offsetWidth-4,e.clientX-wrap.left+16))+'px';if(pin)selectFocus(row.month);}
$('chart').addEventListener('pointermove',e=>hover(e));$('chart').addEventListener('click',e=>hover(e,true));$('chart').addEventListener('pointerleave',()=>{$('tooltip').hidden=true;$('crosshair')?.setAttribute('visibility','hidden');});
$('export').addEventListener('click',()=>{const fields=['month','NASDAQ','SP500','QQQ','FEDFUNDS','NFP','GDP_GROWTH','GDP','GDPC1','GS2','GS10','quarter','partial'];const header=['月份','Nasdaq_点','SP500_点','QQQ_USD_不含分红','联邦基金利率_%_月均','新增非农_千人_季调','实际GDP增速_%_季环比年化','名义GDP_十亿美元_年率','实际GDP_十亿2017美元_年率','2年国债_%_月均','10年国债_%_月均','GDP所属季度','月内暂值','Nasdaq交易日','SP500交易日','QQQ交易日','Nasdaq报价时间','SP500报价时间','QQQ报价时间'];const lines=[header.join(','),...state.range.map(r=>[...fields.map(k=>r[k]??''),...keys.map(k=>r.dates[k]??''),...keys.map(k=>r.times[k]??'')].join(','))];const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`market-atlas_${state.start}_${state.end}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
let refreshing=false;
async function refresh(manual=false){if(refreshing)return;if(state.data&&state.rows.at(-1).month!==nyMonth())setData(state.data);if(location.protocol==='file:'){$('last-checked').textContent='本地快照 · 部署后自动更新';if(manual)notify('当前为本地文件模式，正在展示随附历史快照。部署到 GitHub Pages 后可检查线上数据更新。');return;}refreshing=true;$('refresh').disabled=true;try{const response=await fetch(`data/history.json?v=${Date.now()}`,{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('HTTP '+response.status);const data=validate(await response.json());const changed=data.checkedAt!==state.data?.checkedAt;setData(data,!state.data);if(manual&&!changed&&!data.failedSeries?.length&&(Date.now()-Date.parse(data.dataUpdatedAt))/86400000<=2)notify('已检查线上数据，当前已是最新保存版本。数据抓取由定时任务执行。');}catch{notify(state.data?'无法检查线上更新，继续显示已保存的历史数据。':'无法载入数据。请确认 data/history.json 和 data/history.js 已随网页一起上传。');}finally{refreshing=false;$('refresh').disabled=false;$('last-checked').textContent='上次检查 '+new Date().toLocaleTimeString('zh-CN',{hour12:false})+' · 每分钟检查';}}
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(state.data)renderChart();},100);});
$('refresh').addEventListener('click',()=>refresh(true));try{if(window.MARKET_DATA)setData(window.MARKET_DATA,true);}catch{notify('随附数据文件格式异常，正在尝试读取线上数据。');}refresh();setInterval(()=>{if(!document.hidden)refresh();},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});window.addEventListener('online',()=>refresh());
})();
